obj-$(CONFIG_PANEL_BUG_DVI) += panel-bug-dvi.o
obj-$(CONFIG_PANEL_BUG_VGA) += panel-bug-vga.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_LQ043T1DG01) += panel-sharp-lq043t1dg01.o
obj-$(CONFIG_PANEL_SHARP_SPI_LCD) += panel-sharp-lq025q3dw02.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_TOPPOLY_TDO35S) += panel-toppoly-tdo35s.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_TFP410)		+= tfp410.o
obj-$(CONFIG_THS8200)		+= ths8200.o
